DROP SCHEMA IF EXISTS CUSTOMER_SCHEMA CASCADE;

CREATE SCHEMA CUSTOMER_SCHEMA; 
 
CREATE TABLE CUSTOMER_SCHEMA.customer (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL
);

CREATE TABLE CUSTOMER_SCHEMA.address (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  address1 VARCHAR(250) NOT NULL,
  address2 VARCHAR(250) ,
  city VARCHAR(250) NOT NULL,
  state VARCHAR(250) NOT NULL,
  zip VARCHAR(250) NOT NULL,
  customer_id INT NOT NULL,
  FOREIGN KEY(customer_id) REFERENCES customer_schema.customer(id) ON DELETE CASCADE
);