DROP SCHEMA IF EXISTS EQUIPMENT_SCHEMA CASCADE;

CREATE SCHEMA EQUIPMENT_SCHEMA; 
 
CREATE TABLE EQUIPMENT_SCHEMA.equipment (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customer_id INT NOT NULL,
  name VARCHAR(250) NOT NULL
);